services:
  cqueries:
    image: cqueries:1
    build: 
      context: Companion-Queries/.
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
  
  app:
    build: front-end/.
    ports:
      - "3000:3000"

networks:
    cqueries-network:
        driver: bridge